%--------------------------------------------------------------------------
% GenStrainMap
% 
% Generate a strain map from a given strain_cache.mat generated by
% AnalyzeVideoSegment.m
%--------------------------------------------------------------------------

project_path = uigetdir('', 'Select project directory');
load(fullfile(project_path, 'strain_cache.mat'));

[tFile, tPath] = uigetfile;
load(fullfile(tPath, tFile));

%% Generate strain map

ValRangeX = 1:0.01:(ffd.m - 1);
ValRangeY = 6:0.1:(ffd.m - 1);

tvec = timevec(StartFrameIndx:EndFrameIndx);

StrainMapX = zeros(NumFrames, length(ValRangeX));
StrainMapY = zeros(NumFrames, length(ValRangeX));

[MatMeshX, MatMeshY] = meshgrid(ValRangeX, ValRangeY);
MaterialPoints = [MatMeshX(:), MatMeshY(:)];

for t = 1:NumFrames
    disp(['Processing Frame: ', num2str(t)]);
    Px2 = Px(:,t);
    Py2 = Py(:,t);
    
    [E, lambda] = ffd.CalculateStrain(Px2, Py2, MaterialPoints);
    
    StrainX_2D = reshape(lambda(:,1), length(ValRangeY), length(ValRangeX));
    StrainY_2D = reshape(lambda(:,2), length(ValRangeY), length(ValRangeX));
    
    StrainMapX(t,:) = nanmean(StrainX_2D, 1);
    StrainMapY(t,:) = nanmean(StrainY_2D, 1);
end

%% Display strain map

disp('1: Longitudinal strain');
disp('2: Transverse strain');
strain_indx = input('What strain do you want to plot? ');

if (strain_indx == 2)
    StrainMap = StrainMapY;
else
    StrainMap = StrainMapX;
end

Ref = tvec(1);
tvec = tvec - Ref;

figure;
h = imagesc(StrainMap);
set(h, 'YData', tvec);
ylim([0, max(tvec)]);
xlabel('Length along the small intestine');
ylabel('Time (s)');

cl = [-0.4, 0.4]; %caxis; %[-0.0955, 0.1744];
center = -1 * cl(2) / (cl(1) - cl(2));
mycolormap = customcolormap([0, center, 1], [1, 0, 0; 1, 1, 1; 0, 0, 1]);
colormap(mycolormap);
colorbar;
caxis(cl);

